inherit_from: .rubocop_todo.yml

# Code style checking for RSpec files
# https://github.com/rubocop-hq/rubocop-rspec
require: rubocop-rspec

AllCops:
  Include:
    - lib/**/*.rb
  Exclude:
    - bin/**/*
    - .git/**/*
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
RSpec/ExampleLength:
  Max: 20